#!/bin/bash

export LANG=C

TMPDIR=$(mktemp -d)
trap "rm -rf '${TMPDIR}'" EXIT

KEYSERVER='hkp://pgp.mit.edu:11371'
GPG="gpg --quiet --batch --no-tty --no-permission-warning --keyserver "${KEYSERVER}" --homedir ${TMPDIR}"

pushd "$(dirname "$0")" >/dev/null

$GPG --gen-key <<EOF
%echo Generating MSYS2 Keyring keychain master key...
Key-Type: RSA
Key-Length: 1024
Key-Usage: sign
Name-Real: MSYS2 Keyring Keychain Master Key
Name-Email: msys2-keyring@localhost
Expire-Date: 0
%commit
%echo Done
EOF

rm -rf master packager packager-revoked msys2-trusted msys2-revoked
mkdir master packager packager-revoked

while read -ra data; do
	keyid="${data[0]}"
	username="${data[@]:1}"
	echo "User is $username"
	${GPG} --recv-keys ${keyid} &>/dev/null
	printf 'minimize\nquit\ny\n' | \
		${GPG} --command-fd 0 --edit-key ${keyid}
	${GPG} --yes --lsign-key ${keyid} &>/dev/null
	${GPG} --armor --no-emit-version --export ${keyid} >> master/${username}.asc
	echo "${keyid}:4:" >> msys2-trusted
done < master-keyids
${GPG} --import-ownertrust < msys2-trusted 2>/dev/null

while read -ra data; do
	keyid="${data[0]}"
	${GPG} --recv-keys ${keyid} &>/dev/null
done < packager-keyids
while read -ra data; do
	keyid="${data[0]}"
	username="${data[@]:1}"
	printf 'clean\nquit\ny\n' | \
		${GPG} --command-fd 0 --edit-key ${keyid}
	if ! ${GPG} --list-keys --with-colons ${keyid} 2>/dev/null | grep -q '^pub:f:'; then
		echo "key is not fully trusted: ${keyid} ${username}"
	else
		${GPG} --armor --no-emit-version --export ${keyid} >> packager/${username}.asc
	fi
done < packager-keyids

while read -ra data; do
	keyid="${data[0]}"
	username="${data[1]}"
	${GPG} --recv-keys ${keyid} &>/dev/null
	printf 'clean\nquit\ny\n' | \
		${GPG} --command-fd 0 --edit-key ${keyid}
	if ! ${GPG} --list-keys --with-colons ${keyid} 2>/dev/null | grep -q '^pub:f:'; then
		${GPG} --armor --no-emit-version --export ${keyid} >> packager-revoked/${username}.asc
		echo "${keyid}" >> msys2-revoked
	else
		echo "key is still fully trusted: ${keyid} ${username}"
	fi
done < packager-revoked-keyids

touch msys2-trusted msys2-revoked

cat master/*.asc packager/*.asc packager-revoked/*.asc > msys2.gpg

popd >/dev/null
